#Requires -Version 2.0

<#
    .SYNOPSIS
        Definitions for a portable Android development environment

    .NOTES
        To update a package, update its name and its URL, then execute

            Remove-AndroidStudioPortable.ps1
            Setup-AndroidStudioPortable.ps1

        The configuration directory specified in `$PortableHomeDirectory`
        will be untouched.
 #>

 #Settings folder for Android Studio 
$PortabelHomeDirectoryName =
    'portable-home'
$PortableHomeDirectory =
    ".\$PortabelHomeDirectoryName"

#Locations of Android SDK downloads
$AndroidSDKDirectory =
    ".\android-sdk-windows"
$AndroidSDKBinariesDirectories = @(
    "$AndroidSDKDirectory\tools",
    "$AndroidSDKDirectory\platform-tools"
)

## Android Studio 
$AndroidStudio =
    'android-studio-ide-182.5264788-windows'
$AndroidStudioArchive =
    "$AndroidStudio.zip"
#URL changes based on version above
$AndroidStudioURL =
    "https://dl.google.com/dl/android/studio/ide-zips/3.3.1.0/$AndroidStudioArchive"
## Autogenerated from above
$AndroidStudioDirectory =
    ".\$AndroidStudio\android-studio"
$AndroidStudioBinariesDirectory =
    "$AndroidStudioDirectory\bin"
$AndroidStudioUserHomeDirectory =
    "`${idea.home}/../../$PortabelHomeDirectoryName"
$AndroidStudioHomeDirectory =
    "$AndroidStudioUserHomeDirectory/.AndroidStudio"
$AndroidStudioExecutable =
    'studio64.exe'
$AndroidStudioConfigurationFile =
    "$AndroidStudioDirectory\bin\idea.properties"
$AndroidStudioAdditionalParameters = @(
    "idea.config.path=$AndroidStudioHomeDirectory/config",
    "idea.system.path=$AndroidStudioHomeDirectory/system",
    "idea.plugins.path=$AndroidStudioHomeDirectory/config/plugins"
)
$AndroidStudioVMConfigurationFiles = @(
    "$AndroidStudioDirectory\bin\studio.exe.vmoptions",
    "$AndroidStudioDirectory\bin\studio64.exe.vmoptions"
)
$AndroidStudioAdditionalVMParameters = @(
    "-Duser.home=$AndroidStudioUserHomeDirectory/"
)
$AndroidStudioBatchFile =
    '.\Start-AndroidStudioPortable.bat'

$GradleUserHomeDirectory =
    "$PortableHomeDirectory\.gradle"

	
### Tools Section. Shouldnt need to change ##

##7z File Expander
$7z =
    '7z1900-extra'
	
#Autgenerated from above
$7zInstaller =
    "$7z.7z"
$7zURL =
    "http://d.7-zip.org/a/$7zInstaller"
$7zExecutable =
    '7za.exe'
#$7zExtractFile =				
#    "x64\$7zExecutable"	#64 bit version if desired
$7zExtractFile =
    "$7zExecutable"
$7zBootStrapURL = 
	'https://www.7-zip.org/a/7zr.exe'
$7zBootStrapExec = 
	'7zr.exe'
	
##Aria Downloader
$aria2 =
    'aria2-1.34.0-win-64bit-build1'
$aria2Archive =
    "$aria2.zip"
##URL may need adjusted if newer version is used 
$aria2URL =
    "https://github.com/aria2/aria2/releases/download/release-1.34.0/$aria2Archive"
$aria2Directory =
    ".\$aria2"
$aria2Executable =
    "$aria2\aria2c.exe"
	
